version: '2'
services:

  idp:
    container_name: "idp"

    build: 
      context: ./idp

    volumes:
      - "./idp/shibboleth-idp/conf:/opt/shibboleth-idp/conf"
      - "./idp/shibboleth-idp/metadata:/opt/shibboleth-idp/metadata"
      # - "./idp/shibboleth-idp/credentials:/opt/shibboleth-idp/credentials"
      - "./idp/shibboleth-idp/messages:/opt/shibboleth-idp/messages"
      - "./idp/shibboleth-idp/flows:/opt/shibboleth-idp/flows"
      - "./idp/shibboleth-idp/views:/opt/shibboleth-idp/views"
      - "./idp/shibboleth-idp/edit-webapp/api:/opt/shibboleth-idp/edit-webapp/api"
      - "./idp/shibboleth-idp/edit-webapp/css:/opt/shibboleth-idp/edit-webapp/css"
      - "./idp/shibboleth-idp/edit-webapp/fonts:/opt/shibboleth-idp/edit-webapp/fonts"
      - "./idp/shibboleth-idp/edit-webapp/images/:/opt/shibboleth-idp/edit-webapp/images"
      - "./idp/docker-entrypoint.sh:/docker-entrypoint.sh"

    entrypoint: ./docker-entrypoint.sh

    env_file: ./idp/file.env

    ports:
      - "443:8443"
      - "80:8080"

  ldap:
    container_name : "ldap"

    build:
      context: ./ldap

    ports:
      - "389:389"

  openldap:
    container_name : "openldap"
    
    build:
      context: ./openldap

    ports:
      - "389:389"

