version: '2'
services:
  shibboleth-idp:
    build:
      context: ./idp
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./idp/confs:/opt/shibboleth-idp/conf/"
      - "./idp/metadata:/opt/shibboleth-idp/metadata/"
      - "./idp/docker-entrypoint.sh:/docker-entrypoint.sh"
    container_name: "shibboleth-idp"
    entrypoint: ./docker-entrypoint.sh
    env_file: ./idp/env.env
    logging:
      driver: "journald"
  shibboleth-sp:
    build:
      context: ./sp
    ports:
      - "80:443"
    volumes:
      - "./sp/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
    container_name: "shibboleth-sp"
    entrypoint: "/usr/local/bin/docker-entrypoint.sh"
    logging:
      driver: "journald"
  openldap:
    build:
      context: ./ldap
    volumes:
      - "./ldap/service:/container/service"
      - "./ldap/environment:/container/environment/99-default"
    ports:
      - "389:389"
      - "636:636"
#   entrypoint: insert a entrypoint
    container_name : "openldap"
